Fix Secureboot causing image load issue on platform that does not require secureboot
This is to fix a cherry-pick error where some changes got left out which causes the image not able to load on pizzabox platforms failling with following messages:

Loading SONiC-OS OS kernel ...Loading SONiC-OS OS kernel ...



error: can't find command `linuxefi'.
error: can't find command `linuxefi'.
Loading SONiC-OS OS initial ramdisk ...Loading SONiC-OS OS initial ramdisk ...